# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/MB/MB.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MB || ORIG_REF_NAME==MB} -quiet] -quiet

# IP: bd/MB/ip/MB_clk_wiz_0_0/MB_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MB_clk_wiz_0_0 || ORIG_REF_NAME==MB_clk_wiz_0_0} -quiet] -quiet

# IP: bd/MB/ip/MB_rst_clk_wiz_0_100M_0/MB_rst_clk_wiz_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MB_rst_clk_wiz_0_100M_0 || ORIG_REF_NAME==MB_rst_clk_wiz_0_100M_0} -quiet] -quiet

# IP: bd/MB/ip/MB_axi_uartlite_0_0/MB_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MB_axi_uartlite_0_0 || ORIG_REF_NAME==MB_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/MB/ip/MB_axi_bram_ctrl_0_1/MB_axi_bram_ctrl_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MB_axi_bram_ctrl_0_1 || ORIG_REF_NAME==MB_axi_bram_ctrl_0_1} -quiet] -quiet

# IP: bd/MB/ip/MB_axi_bram_ctrl_0_bram_1/MB_axi_bram_ctrl_0_bram_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MB_axi_bram_ctrl_0_bram_1 || ORIG_REF_NAME==MB_axi_bram_ctrl_0_bram_1} -quiet] -quiet

# IP: bd/MB/ip/MB_microblaze_0_5/MB_microblaze_0_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MB_microblaze_0_5 || ORIG_REF_NAME==MB_microblaze_0_5} -quiet] -quiet

# IP: bd/MB/ip/MB_dlmb_v10_7/MB_dlmb_v10_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MB_dlmb_v10_7 || ORIG_REF_NAME==MB_dlmb_v10_7} -quiet] -quiet

# IP: bd/MB/ip/MB_ilmb_v10_7/MB_ilmb_v10_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MB_ilmb_v10_7 || ORIG_REF_NAME==MB_ilmb_v10_7} -quiet] -quiet

# IP: bd/MB/ip/MB_dlmb_bram_if_cntlr_7/MB_dlmb_bram_if_cntlr_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MB_dlmb_bram_if_cntlr_7 || ORIG_REF_NAME==MB_dlmb_bram_if_cntlr_7} -quiet] -quiet

# IP: bd/MB/ip/MB_ilmb_bram_if_cntlr_7/MB_ilmb_bram_if_cntlr_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MB_ilmb_bram_if_cntlr_7 || ORIG_REF_NAME==MB_ilmb_bram_if_cntlr_7} -quiet] -quiet

# IP: bd/MB/ip/MB_lmb_bram_7/MB_lmb_bram_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MB_lmb_bram_7 || ORIG_REF_NAME==MB_lmb_bram_7} -quiet] -quiet

# IP: bd/MB/ip/MB_mdm_1_5/MB_mdm_1_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MB_mdm_1_5 || ORIG_REF_NAME==MB_mdm_1_5} -quiet] -quiet

# IP: bd/MB/ip/MB_axi_smc_2/MB_axi_smc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MB_axi_smc_2 || ORIG_REF_NAME==MB_axi_smc_2} -quiet] -quiet

# IP: bd/MB/ip/MB_hello_world_writer_0_4/MB_hello_world_writer_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MB_hello_world_writer_0_4 || ORIG_REF_NAME==MB_hello_world_writer_0_4} -quiet] -quiet

# XDC: c:/Users/gavwa/Desktop/Workin_Dir/Hardware/MicroBlaze/MicroBlaze.gen/sources_1/bd/MB/MB_ooc.xdc
