# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/Users/gavwa/Desktop/Workin_Dir/Hardware/MicroBlaze/MicroBlaze.runs/synth_1/MB_wrapper.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 6
set_param xicom.use_bs_reader 1
set_param bd.open.in_stealth_mode 1
set_msg_config -id {HDL-1065} -limit 10000
set_msg_config  -id {[BD 41-1306]}  -suppress 
set_msg_config  -id {[BD 41-1271]}  -suppress 
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/gavwa/Desktop/Workin_Dir/Hardware/MicroBlaze/MicroBlaze.cache/wt [current_project]
set_property parent.project_path C:/Users/gavwa/Desktop/Workin_Dir/Hardware/MicroBlaze/MicroBlaze.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part_repo_paths {C:/Users/gavwa/AppData/Roaming/Xilinx/Vivado/2024.1/xhub/board_store/xilinx_board_store} [current_project]
set_property board_part digilentinc.com:basys3:part0:1.2 [current_project]
set_property ip_output_repo c:/Users/gavwa/Desktop/Workin_Dir/Hardware/MicroBlaze/MicroBlaze.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib C:/Users/gavwa/Desktop/Workin_Dir/Hardware/MicroBlaze/MicroBlaze.gen/sources_1/bd/MB/hdl/MB_wrapper.v
add_files C:/Users/gavwa/Desktop/Workin_Dir/Hardware/MicroBlaze/MicroBlaze.srcs/sources_1/bd/MB/MB.bd
set_property used_in_implementation false [get_files -all c:/Users/gavwa/Desktop/Workin_Dir/Hardware/MicroBlaze/MicroBlaze.gen/sources_1/bd/MB/ip/MB_clk_wiz_0_0/MB_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gavwa/Desktop/Workin_Dir/Hardware/MicroBlaze/MicroBlaze.gen/sources_1/bd/MB/ip/MB_clk_wiz_0_0/MB_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gavwa/Desktop/Workin_Dir/Hardware/MicroBlaze/MicroBlaze.gen/sources_1/bd/MB/ip/MB_clk_wiz_0_0/MB_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gavwa/Desktop/Workin_Dir/Hardware/MicroBlaze/MicroBlaze.gen/sources_1/bd/MB/ip/MB_rst_clk_wiz_0_100M_0/MB_rst_clk_wiz_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gavwa/Desktop/Workin_Dir/Hardware/MicroBlaze/MicroBlaze.gen/sources_1/bd/MB/ip/MB_rst_clk_wiz_0_100M_0/MB_rst_clk_wiz_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gavwa/Desktop/Workin_Dir/Hardware/MicroBlaze/MicroBlaze.gen/sources_1/bd/MB/ip/MB_rst_clk_wiz_0_100M_0/MB_rst_clk_wiz_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gavwa/Desktop/Workin_Dir/Hardware/MicroBlaze/MicroBlaze.gen/sources_1/bd/MB/ip/MB_axi_uartlite_0_0/MB_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gavwa/Desktop/Workin_Dir/Hardware/MicroBlaze/MicroBlaze.gen/sources_1/bd/MB/ip/MB_axi_uartlite_0_0/MB_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gavwa/Desktop/Workin_Dir/Hardware/MicroBlaze/MicroBlaze.gen/sources_1/bd/MB/ip/MB_axi_uartlite_0_0/MB_axi_uartlite_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gavwa/Desktop/Workin_Dir/Hardware/MicroBlaze/MicroBlaze.gen/sources_1/bd/MB/ip/MB_axi_bram_ctrl_0_1/MB_axi_bram_ctrl_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gavwa/Desktop/Workin_Dir/Hardware/MicroBlaze/MicroBlaze.gen/sources_1/bd/MB/ip/MB_axi_bram_ctrl_0_bram_1/MB_axi_bram_ctrl_0_bram_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gavwa/Desktop/Workin_Dir/Hardware/MicroBlaze/MicroBlaze.gen/sources_1/bd/MB/ip/MB_microblaze_0_5/MB_microblaze_0_5.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gavwa/Desktop/Workin_Dir/Hardware/MicroBlaze/MicroBlaze.gen/sources_1/bd/MB/ip/MB_microblaze_0_5/MB_microblaze_0_5_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gavwa/Desktop/Workin_Dir/Hardware/MicroBlaze/MicroBlaze.gen/sources_1/bd/MB/ip/MB_microblaze_0_5/MB_microblaze_0_5_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gavwa/Desktop/Workin_Dir/Hardware/MicroBlaze/MicroBlaze.gen/sources_1/bd/MB/ip/MB_dlmb_v10_7/MB_dlmb_v10_7_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gavwa/Desktop/Workin_Dir/Hardware/MicroBlaze/MicroBlaze.gen/sources_1/bd/MB/ip/MB_ilmb_v10_7/MB_ilmb_v10_7_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gavwa/Desktop/Workin_Dir/Hardware/MicroBlaze/MicroBlaze.gen/sources_1/bd/MB/ip/MB_dlmb_bram_if_cntlr_7/MB_dlmb_bram_if_cntlr_7_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gavwa/Desktop/Workin_Dir/Hardware/MicroBlaze/MicroBlaze.gen/sources_1/bd/MB/ip/MB_ilmb_bram_if_cntlr_7/MB_ilmb_bram_if_cntlr_7_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gavwa/Desktop/Workin_Dir/Hardware/MicroBlaze/MicroBlaze.gen/sources_1/bd/MB/ip/MB_lmb_bram_7/MB_lmb_bram_7_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gavwa/Desktop/Workin_Dir/Hardware/MicroBlaze/MicroBlaze.gen/sources_1/bd/MB/ip/MB_mdm_1_5/MB_mdm_1_5.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gavwa/Desktop/Workin_Dir/Hardware/MicroBlaze/MicroBlaze.gen/sources_1/bd/MB/ip/MB_mdm_1_5/MB_mdm_1_5_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gavwa/Desktop/Workin_Dir/Hardware/MicroBlaze/MicroBlaze.gen/sources_1/bd/MB/ip/MB_axi_smc_2/bd_0/ip/ip_1/bd_0186_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gavwa/Desktop/Workin_Dir/Hardware/MicroBlaze/MicroBlaze.gen/sources_1/bd/MB/ip/MB_axi_smc_2/bd_0/ip/ip_1/bd_0186_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gavwa/Desktop/Workin_Dir/Hardware/MicroBlaze/MicroBlaze.gen/sources_1/bd/MB/ip/MB_axi_smc_2/bd_0/ip/ip_2/bd_0186_arinsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gavwa/Desktop/Workin_Dir/Hardware/MicroBlaze/MicroBlaze.gen/sources_1/bd/MB/ip/MB_axi_smc_2/bd_0/ip/ip_3/bd_0186_rinsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gavwa/Desktop/Workin_Dir/Hardware/MicroBlaze/MicroBlaze.gen/sources_1/bd/MB/ip/MB_axi_smc_2/bd_0/ip/ip_4/bd_0186_awinsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gavwa/Desktop/Workin_Dir/Hardware/MicroBlaze/MicroBlaze.gen/sources_1/bd/MB/ip/MB_axi_smc_2/bd_0/ip/ip_5/bd_0186_winsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gavwa/Desktop/Workin_Dir/Hardware/MicroBlaze/MicroBlaze.gen/sources_1/bd/MB/ip/MB_axi_smc_2/bd_0/ip/ip_6/bd_0186_binsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gavwa/Desktop/Workin_Dir/Hardware/MicroBlaze/MicroBlaze.gen/sources_1/bd/MB/ip/MB_axi_smc_2/bd_0/ip/ip_7/bd_0186_aroutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gavwa/Desktop/Workin_Dir/Hardware/MicroBlaze/MicroBlaze.gen/sources_1/bd/MB/ip/MB_axi_smc_2/bd_0/ip/ip_8/bd_0186_routsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gavwa/Desktop/Workin_Dir/Hardware/MicroBlaze/MicroBlaze.gen/sources_1/bd/MB/ip/MB_axi_smc_2/bd_0/ip/ip_9/bd_0186_awoutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gavwa/Desktop/Workin_Dir/Hardware/MicroBlaze/MicroBlaze.gen/sources_1/bd/MB/ip/MB_axi_smc_2/bd_0/ip/ip_10/bd_0186_woutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gavwa/Desktop/Workin_Dir/Hardware/MicroBlaze/MicroBlaze.gen/sources_1/bd/MB/ip/MB_axi_smc_2/bd_0/ip/ip_11/bd_0186_boutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gavwa/Desktop/Workin_Dir/Hardware/MicroBlaze/MicroBlaze.gen/sources_1/bd/MB/ip/MB_axi_smc_2/bd_0/ip/ip_12/bd_0186_arni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gavwa/Desktop/Workin_Dir/Hardware/MicroBlaze/MicroBlaze.gen/sources_1/bd/MB/ip/MB_axi_smc_2/bd_0/ip/ip_12/bd_0186_arni_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gavwa/Desktop/Workin_Dir/Hardware/MicroBlaze/MicroBlaze.gen/sources_1/bd/MB/ip/MB_axi_smc_2/bd_0/ip/ip_13/bd_0186_rni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gavwa/Desktop/Workin_Dir/Hardware/MicroBlaze/MicroBlaze.gen/sources_1/bd/MB/ip/MB_axi_smc_2/bd_0/ip/ip_13/bd_0186_rni_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gavwa/Desktop/Workin_Dir/Hardware/MicroBlaze/MicroBlaze.gen/sources_1/bd/MB/ip/MB_axi_smc_2/bd_0/ip/ip_14/bd_0186_awni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gavwa/Desktop/Workin_Dir/Hardware/MicroBlaze/MicroBlaze.gen/sources_1/bd/MB/ip/MB_axi_smc_2/bd_0/ip/ip_14/bd_0186_awni_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gavwa/Desktop/Workin_Dir/Hardware/MicroBlaze/MicroBlaze.gen/sources_1/bd/MB/ip/MB_axi_smc_2/bd_0/ip/ip_15/bd_0186_wni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gavwa/Desktop/Workin_Dir/Hardware/MicroBlaze/MicroBlaze.gen/sources_1/bd/MB/ip/MB_axi_smc_2/bd_0/ip/ip_15/bd_0186_wni_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gavwa/Desktop/Workin_Dir/Hardware/MicroBlaze/MicroBlaze.gen/sources_1/bd/MB/ip/MB_axi_smc_2/bd_0/ip/ip_16/bd_0186_bni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gavwa/Desktop/Workin_Dir/Hardware/MicroBlaze/MicroBlaze.gen/sources_1/bd/MB/ip/MB_axi_smc_2/bd_0/ip/ip_16/bd_0186_bni_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gavwa/Desktop/Workin_Dir/Hardware/MicroBlaze/MicroBlaze.gen/sources_1/bd/MB/ip/MB_axi_smc_2/bd_0/ip/ip_20/bd_0186_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gavwa/Desktop/Workin_Dir/Hardware/MicroBlaze/MicroBlaze.gen/sources_1/bd/MB/ip/MB_axi_smc_2/bd_0/ip/ip_21/bd_0186_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gavwa/Desktop/Workin_Dir/Hardware/MicroBlaze/MicroBlaze.gen/sources_1/bd/MB/ip/MB_axi_smc_2/bd_0/ip/ip_21/bd_0186_sarn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gavwa/Desktop/Workin_Dir/Hardware/MicroBlaze/MicroBlaze.gen/sources_1/bd/MB/ip/MB_axi_smc_2/bd_0/ip/ip_22/bd_0186_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gavwa/Desktop/Workin_Dir/Hardware/MicroBlaze/MicroBlaze.gen/sources_1/bd/MB/ip/MB_axi_smc_2/bd_0/ip/ip_22/bd_0186_srn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gavwa/Desktop/Workin_Dir/Hardware/MicroBlaze/MicroBlaze.gen/sources_1/bd/MB/ip/MB_axi_smc_2/bd_0/ip/ip_23/bd_0186_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gavwa/Desktop/Workin_Dir/Hardware/MicroBlaze/MicroBlaze.gen/sources_1/bd/MB/ip/MB_axi_smc_2/bd_0/ip/ip_23/bd_0186_sawn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gavwa/Desktop/Workin_Dir/Hardware/MicroBlaze/MicroBlaze.gen/sources_1/bd/MB/ip/MB_axi_smc_2/bd_0/ip/ip_24/bd_0186_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gavwa/Desktop/Workin_Dir/Hardware/MicroBlaze/MicroBlaze.gen/sources_1/bd/MB/ip/MB_axi_smc_2/bd_0/ip/ip_24/bd_0186_swn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gavwa/Desktop/Workin_Dir/Hardware/MicroBlaze/MicroBlaze.gen/sources_1/bd/MB/ip/MB_axi_smc_2/bd_0/ip/ip_25/bd_0186_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gavwa/Desktop/Workin_Dir/Hardware/MicroBlaze/MicroBlaze.gen/sources_1/bd/MB/ip/MB_axi_smc_2/bd_0/ip/ip_25/bd_0186_sbn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gavwa/Desktop/Workin_Dir/Hardware/MicroBlaze/MicroBlaze.gen/sources_1/bd/MB/ip/MB_axi_smc_2/bd_0/ip/ip_29/bd_0186_s01a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gavwa/Desktop/Workin_Dir/Hardware/MicroBlaze/MicroBlaze.gen/sources_1/bd/MB/ip/MB_axi_smc_2/bd_0/ip/ip_30/bd_0186_sawn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gavwa/Desktop/Workin_Dir/Hardware/MicroBlaze/MicroBlaze.gen/sources_1/bd/MB/ip/MB_axi_smc_2/bd_0/ip/ip_30/bd_0186_sawn_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gavwa/Desktop/Workin_Dir/Hardware/MicroBlaze/MicroBlaze.gen/sources_1/bd/MB/ip/MB_axi_smc_2/bd_0/ip/ip_31/bd_0186_swn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gavwa/Desktop/Workin_Dir/Hardware/MicroBlaze/MicroBlaze.gen/sources_1/bd/MB/ip/MB_axi_smc_2/bd_0/ip/ip_31/bd_0186_swn_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gavwa/Desktop/Workin_Dir/Hardware/MicroBlaze/MicroBlaze.gen/sources_1/bd/MB/ip/MB_axi_smc_2/bd_0/ip/ip_32/bd_0186_sbn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gavwa/Desktop/Workin_Dir/Hardware/MicroBlaze/MicroBlaze.gen/sources_1/bd/MB/ip/MB_axi_smc_2/bd_0/ip/ip_32/bd_0186_sbn_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gavwa/Desktop/Workin_Dir/Hardware/MicroBlaze/MicroBlaze.gen/sources_1/bd/MB/ip/MB_axi_smc_2/bd_0/ip/ip_33/bd_0186_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gavwa/Desktop/Workin_Dir/Hardware/MicroBlaze/MicroBlaze.gen/sources_1/bd/MB/ip/MB_axi_smc_2/bd_0/ip/ip_34/bd_0186_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gavwa/Desktop/Workin_Dir/Hardware/MicroBlaze/MicroBlaze.gen/sources_1/bd/MB/ip/MB_axi_smc_2/bd_0/ip/ip_34/bd_0186_m00arn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gavwa/Desktop/Workin_Dir/Hardware/MicroBlaze/MicroBlaze.gen/sources_1/bd/MB/ip/MB_axi_smc_2/bd_0/ip/ip_35/bd_0186_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gavwa/Desktop/Workin_Dir/Hardware/MicroBlaze/MicroBlaze.gen/sources_1/bd/MB/ip/MB_axi_smc_2/bd_0/ip/ip_35/bd_0186_m00rn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gavwa/Desktop/Workin_Dir/Hardware/MicroBlaze/MicroBlaze.gen/sources_1/bd/MB/ip/MB_axi_smc_2/bd_0/ip/ip_36/bd_0186_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gavwa/Desktop/Workin_Dir/Hardware/MicroBlaze/MicroBlaze.gen/sources_1/bd/MB/ip/MB_axi_smc_2/bd_0/ip/ip_36/bd_0186_m00awn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gavwa/Desktop/Workin_Dir/Hardware/MicroBlaze/MicroBlaze.gen/sources_1/bd/MB/ip/MB_axi_smc_2/bd_0/ip/ip_37/bd_0186_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gavwa/Desktop/Workin_Dir/Hardware/MicroBlaze/MicroBlaze.gen/sources_1/bd/MB/ip/MB_axi_smc_2/bd_0/ip/ip_37/bd_0186_m00wn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gavwa/Desktop/Workin_Dir/Hardware/MicroBlaze/MicroBlaze.gen/sources_1/bd/MB/ip/MB_axi_smc_2/bd_0/ip/ip_38/bd_0186_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gavwa/Desktop/Workin_Dir/Hardware/MicroBlaze/MicroBlaze.gen/sources_1/bd/MB/ip/MB_axi_smc_2/bd_0/ip/ip_38/bd_0186_m00bn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gavwa/Desktop/Workin_Dir/Hardware/MicroBlaze/MicroBlaze.gen/sources_1/bd/MB/ip/MB_axi_smc_2/bd_0/ip/ip_40/bd_0186_m01s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gavwa/Desktop/Workin_Dir/Hardware/MicroBlaze/MicroBlaze.gen/sources_1/bd/MB/ip/MB_axi_smc_2/bd_0/ip/ip_41/bd_0186_m01arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gavwa/Desktop/Workin_Dir/Hardware/MicroBlaze/MicroBlaze.gen/sources_1/bd/MB/ip/MB_axi_smc_2/bd_0/ip/ip_41/bd_0186_m01arn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gavwa/Desktop/Workin_Dir/Hardware/MicroBlaze/MicroBlaze.gen/sources_1/bd/MB/ip/MB_axi_smc_2/bd_0/ip/ip_42/bd_0186_m01rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gavwa/Desktop/Workin_Dir/Hardware/MicroBlaze/MicroBlaze.gen/sources_1/bd/MB/ip/MB_axi_smc_2/bd_0/ip/ip_42/bd_0186_m01rn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gavwa/Desktop/Workin_Dir/Hardware/MicroBlaze/MicroBlaze.gen/sources_1/bd/MB/ip/MB_axi_smc_2/bd_0/ip/ip_43/bd_0186_m01awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gavwa/Desktop/Workin_Dir/Hardware/MicroBlaze/MicroBlaze.gen/sources_1/bd/MB/ip/MB_axi_smc_2/bd_0/ip/ip_43/bd_0186_m01awn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gavwa/Desktop/Workin_Dir/Hardware/MicroBlaze/MicroBlaze.gen/sources_1/bd/MB/ip/MB_axi_smc_2/bd_0/ip/ip_44/bd_0186_m01wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gavwa/Desktop/Workin_Dir/Hardware/MicroBlaze/MicroBlaze.gen/sources_1/bd/MB/ip/MB_axi_smc_2/bd_0/ip/ip_44/bd_0186_m01wn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gavwa/Desktop/Workin_Dir/Hardware/MicroBlaze/MicroBlaze.gen/sources_1/bd/MB/ip/MB_axi_smc_2/bd_0/ip/ip_45/bd_0186_m01bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gavwa/Desktop/Workin_Dir/Hardware/MicroBlaze/MicroBlaze.gen/sources_1/bd/MB/ip/MB_axi_smc_2/bd_0/ip/ip_45/bd_0186_m01bn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gavwa/Desktop/Workin_Dir/Hardware/MicroBlaze/MicroBlaze.gen/sources_1/bd/MB/ip/MB_axi_smc_2/ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gavwa/Desktop/Workin_Dir/Hardware/MicroBlaze/MicroBlaze.gen/sources_1/bd/MB/ip/MB_axi_smc_2/smartconnect.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gavwa/Desktop/Workin_Dir/Hardware/MicroBlaze/MicroBlaze.gen/sources_1/bd/MB/MB_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gavwa/Desktop/Workin_Dir/Hardware/MicroBlaze/MicroBlaze.gen/sources_1/bd/MB/ip/MB_microblaze_0_5/data/mb_bootloop_le.elf]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental C:/Users/gavwa/Desktop/Workin_Dir/Hardware/MicroBlaze/MicroBlaze.srcs/utils_1/imports/synth_1/MB_wrapper.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top MB_wrapper -part xc7a35tcpg236-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef MB_wrapper.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file MB_wrapper_utilization_synth.rpt -pb MB_wrapper_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
